### ISSUE TITLE
Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@eca50d2 that was originally registered here. Are you missing a call to unregisterReceiver()?

### ISSUE THREAD

**Issue by amanngoel** [razorpay/razorpay-capacitor#21]
I am unable to complete the payment in Ionic Capacitor 2 app. The exact error logged in Android Studio is:
`E/ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@ebe0007 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@ebe0007 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1437)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1214)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1486)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1459)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:646)
        at com.razorpay.CheckoutPresenterImpl$8.onFinish(CheckoutPresenterImpl.java:764)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@eca50d2 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@eca50d2 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1437)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1214)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1486)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1459)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1447)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:633)
        at com.razorpay.CheckoutPresenterImpl.onSubmit(CheckoutPresenterImpl.java:922)
        at com.razorpay.CheckoutBridge$10.secure(CheckoutBridge.java:157)
        at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1221)
        at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:49)
        at com.razorpay.CheckoutPresenterImpl$17.run(CheckoutPresenterImpl.java:1207)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
`

**Comment by hitesh-webRepo** [comment]
How to resolve this issue ?
